// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloSignController from "./hello_sign_controller"
application.register("hello-sign", HelloSignController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
